---
title: "The ultimate wonder of the cosmos"
listing: 
  contents: posts # all Quarto docs in the `posts` directory will be included on your listing page
  type: grid # or `default` or `table`; each type has its own set of yaml options to include
  sort: "date desc" # can also sort on more than one field
  categories: true # allows you to sort posts by assigned categories 
  feed: true
format:
  html:
    page-layout: full
    code-fold: true
    fontsize: 1.25em
    linestretch: 1.5
    code-line-numbers: true
    code-block-border-left: "#31BAE9"
    code-block-bg: "#000000"
    highlight-style: github
---

Welcome! 

This is the personal blog of Dr. Jorge Abreu Vicente. I see the blog as a window to communicate with you, not as a tool to only share my work. As such, this blog will have different topics on it. From the wonders of the cosmos in Astronomy, to the ultimate wonder of the cosmos: life itself. But it will not be only about Astronomy and Biology. I will bring machine learning, coding, and AI too since they are my current working tools. 
During the winter season I will bring the observation diary of a backyard amateur astronomer. And the content of the blog will also be filled with other topics such as opinions or career advice. 

I hope you like this space and please, make sure to share your thoughs. 

Best! ! !

Jorge

Check [this link](https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/) for details on the listings page