---
title: "Punto vernal: Astronomía, biología, IA y más..."
subtitle: De las maravillas cósmicas a la maravilla definitiva de nuestro cosmos, la vida misma
listing: 
  contents: es/proyectos # all Quarto docs in the `posts` directory will be included on your listing page
  type: default # or `default` or `table`; each type has its own set of yaml options to include
  sort: "date desc" # can also sort on more than one field
  categories: true # allows you to sort posts by assigned categories 
  feed: true
  fields: [image, image-alt, file-modified, date, title, description, author, reading-time]
  page-size: 16
lang: es
format:
  html:
    page-layout: full
    code-fold: true
    linestretch: 1.5
    fontsize: 1em
    code-line-numbers: true
    code-block-border-left: "#31BAE9"
    code-block-bg: "#000000"
    highlight-style: github
---

Bienvenid`@`s! 

Este es el blog personal de Dr. Jorge Abreu Vicente. Mi visión del blog es más como una ventana de comunicación de ideas y opiniones que como publicidad de mi trabajo. Es por ello que este blog ofrecerá temas muy diferentes para una amplia audiencia. El blog tratará temas desde las maravillas cósmicas de la astronomía a la maravilla cósmica definitiva: la vida misma. Además de Astronomía y Biología, el blog tratará también inteligencia artificial, desarrollo y diversos temas de opinión o consejos curriculares.
Durante la temporada innvernal intentaré compartir mi cuaderno de bitácora de observaciones astronómicas *amateurs* en el jardín de casa.

Espero que os guste este espacio y que todos podamos aprender juntos con buestos comentarios!

Cielos claros !

Jorge

------

<!-- Check [this link](https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/) for details on the listings page -->