#!/usr/bin/env python3
"""
embed-equipment.py — Generate TypeScript data files from scraped AstroShop JSON.
Run from web/: python scripts/embed-equipment.py

image_url backfilled from html_cache by build-your-scope/add_image_urls.py.
"""
import json
import os
import argparse
import re


def load(data_dir, fname):
    path = os.path.join(data_dir, fname)
    if not os.path.exists(path):
        return []
    return json.load(open(path, encoding='utf-8'))


def js(v):
    """Serialize a Python value to a JS literal."""
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, str):
        escaped = v.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n').replace('\r', '')
        return f"'{escaped}'"
    if isinstance(v, float):
        if v == int(v):
            return str(int(v))
        return repr(v)
    return repr(v)


def obj_to_ts(d):
    pairs = ', '.join(f'{k}: {js(v)}' for k, v in d.items())
    return f'{{ {pairs} }}'


def normalize_connection(raw):
    """Normalize messy AstroShop connection strings to canonical forms."""
    if raw is None:
        return None
    s = str(raw).strip()
    # T2 variants
    if re.search(r'T[\s-]?2|M42', s, re.IGNORECASE):
        return 'T2'
    # SCT / SC Thread
    if re.search(r'SCT|SC[\s]Thread|Schmidt', s, re.IGNORECASE):
        return 'SCT'
    # 1.25 inch
    if re.search(r'1[,.]25|1¼|1\.25|1,25', s, re.IGNORECASE):
        return '1.25inch'
    # 2 inch
    if re.search(r'^2[\s""]|^2$|2[\s-]inch|2"', s, re.IGNORECASE):
        return '2inch'
    # M48 / M54 / M68 etc
    m = re.match(r'^(M\d+)', s, re.IGNORECASE)
    if m:
        return m.group(1).upper()
    return s


def barrel_to_connection(barrel_inch):
    """Convert numeric barrel diameter in inches to connection string."""
    if barrel_inch is None:
        return None
    if float(barrel_inch) >= 2.0:
        return '2inch'
    return '1.25inch'


def normalize_mount_type(raw):
    if raw is None:
        return None
    s = str(raw).lower()
    if 'dobson' in s:
        return 'dobsonian'
    if ('alt' in s or 'az' in s) and ('goto' in s or 'go-to' in s):
        return 'altaz_goto'
    if 'alt' in s or ('az' in s and 'eq' not in s):
        return 'altaz'
    if ('eq' in s or 'equatorial' in s) and ('goto' in s or 'go-to' in s or 'motor' in s):
        return 'eq_goto'
    if 'eq' in s or 'equatorial' in s:
        return 'eq_manual'
    return None


# Fallback GOTO keywords — used only when mount_goto is absent from JSON
# (old scrapes without multi-category data).  After re-scraping with
# --multi-category this is never needed.
_GOTO_KEYWORDS_FALLBACK = [
    'goto', 'go-to', 'nexstar', 'synscan', 'heq5', 'eq6', 'eq8',
    'cgx', 'cgem', 'avx', 'cem', 'az-gti', 'az-eq',
]

def bundled_mount_type(r):
    """Return the normalized MountType for a bundled scope, or None if OTA-only."""
    is_ota = r.get('is_ota_only')
    if is_ota is None:
        is_ota = True
    if is_ota:
        return None
    base = normalize_mount_type(r.get('mount_type'))
    # Prefer the authoritative mount_goto field (set by --multi-category scrape);
    # fall back to name-keyword detection for older JSON that lacks this field.
    mount_goto = r.get('mount_goto')
    if mount_goto is None:
        name = (r.get('full_name') or '').lower()
        mount_goto = any(kw in name for kw in _GOTO_KEYWORDS_FALLBACK)
    if mount_goto:
        if base == 'altaz':
            return 'altaz_goto'
        if base == 'eq_manual':
            return 'eq_goto'
    return base


def dedup(records):
    """Remove duplicate records by id, keeping first occurrence."""
    seen = set()
    out = []
    for r in records:
        rid = r.get('id')
        if rid and rid in seen:
            continue
        if rid:
            seen.add(rid)
        out.append(r)
    return out


def write_ts(out_dir, fname, varname, typename, records):
    records = dedup(records)
    lines = [
        '// Auto-generated by scripts/embed-equipment.py — do not edit manually',
        f"import type {{ {typename} }} from '@/lib/simulator/types';",
        '',
        f'export const {varname}: {typename}[] = [',
    ]
    for r in records:
        lines.append(f'  {obj_to_ts(r)},')
    lines.append('];')
    path = os.path.join(out_dir, fname)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'  {fname}: {len(records)} records')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data-dir', default='../build-your-scope/data')
    parser.add_argument('--out', default='src/data/simulator')
    args = parser.parse_args()

    data_dir = args.data_dir
    out_dir = args.out
    os.makedirs(out_dir, exist_ok=True)

    # ── Telescopes ──────────────────────────────────────────────────────────
    raw = load(data_dir, 'telescopes.json')
    recs = []
    for r in raw:
        if not r.get('aperture_mm') or not r.get('focal_length_mm'):
            continue
        fr = r.get('focal_ratio')
        if fr is None and r['focal_length_mm'] and r['aperture_mm']:
            fr = round(r['focal_length_mm'] / r['aperture_mm'], 1)
        # prefer tube_weight_kg, fall back to total_weight_kg
        weight = r.get('tube_weight_kg') or r.get('total_weight_kg')
        recs.append({
            'id':        str(r['astroshop_id']),
            'name':      (r.get('full_name') or '')[:60],
            'brand':     r.get('brand') or '',
            'design':    r.get('optical_design') or '',
            'aperture':  r['aperture_mm'],
            'fl':        r['focal_length_mm'],
            'fr':        fr,
            'rear':      normalize_connection(r.get('rear_connection_thread')),
            'bf':        r.get('backfocus_available_mm'),
            'weight_kg': weight,
            'image_url':   r.get('image_url'),
            'price':       r.get('price_eur') or 0,
            'url':         r.get('url') or '',
            'imaging':     r.get('is_imaging_scope'),
            'is_ota_only': r.get('is_ota_only') if r.get('is_ota_only') is not None else True,
            'bundled_mount_type': bundled_mount_type(r),
        })
    write_ts(out_dir, 'telescopes.ts', 'TELESCOPES', 'Telescope', recs)

    # ── Cameras ──────────────────────────────────────────────────────────────
    raw = load(data_dir, 'cameras.json')
    recs = []
    for r in raw:
        if not r.get('sensor_width_mm') or not r.get('sensor_height_mm') or not r.get('pixel_size_um'):
            continue
        recs.append({
            'id':         str(r['astroshop_id']),
            'name':       (r.get('full_name') or '')[:60],
            'brand':      r.get('brand') or '',
            'w':          r['sensor_width_mm'],
            'h':          r['sensor_height_mm'],
            'px':         r['pixel_size_um'],
            'mpx':        r.get('resolution_mpx'),
            'color':      bool(r.get('is_color')),
            'cooling':    bool(r.get('cooling')),
            'connection': normalize_connection(r.get('telescope_connection')),
            'flange':     r.get('flange_focal_distance_mm') or 0,
            'category':   r.get('camera_category') or '',
            'image_url':  r.get('image_url'),
            'price':      r.get('price_eur') or 0,
            'url':        r.get('url') or '',
        })
    write_ts(out_dir, 'cameras.ts', 'CAMERAS', 'Camera', recs)

    # ── Barlows ───────────────────────────────────────────────────────────────
    raw = load(data_dir, 'barlows.json')
    recs = []
    for r in raw:
        if r.get('magnification') is None or not r.get('price_eur'):
            continue
        barrel = r.get('barrel_diameter_inch') or 1.25
        recs.append({
            'id':            str(r['astroshop_id']),
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'factor':        r['magnification'],
            'barrel':        barrel,
            'connectionIn':  barrel_to_connection(barrel),
            'connectionOut': normalize_connection(r.get('camera_connection')) or 'T2',
            'image_url':     r.get('image_url'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'barlows.ts', 'BARLOWS', 'Barlow', recs)

    # ── Correctors ────────────────────────────────────────────────────────────
    raw = load(data_dir, 'correctors.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        # focal_reduction: None for pure flatteners → use 1.0
        factor = r.get('focal_reduction')
        if factor is None:
            factor = 1.0
        recs.append({
            'id':            str(r['astroshop_id']),
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'correctorType': r.get('corrector_type') or '',
            'factor':        factor,
            'connectionIn':  normalize_connection(r.get('telescope_connection')),
            'connectionOut': normalize_connection(r.get('camera_connection')),
            'backfocus':     r.get('focal_plane_distance_mm'),
            'image_url':     r.get('image_url'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'correctors.ts', 'CORRECTORS', 'Corrector', recs)

    # ── Adapters (adapters.json + camera_adaptors.json combined) ──────────────
    raw_a = load(data_dir, 'adapters.json')
    raw_ca = load(data_dir, 'camera_adaptors.json')
    recs = []
    seen = set()
    for r in raw_a:
        if not r.get('price_eur'):
            continue
        rid = str(r['astroshop_id'])
        if rid in seen:
            continue
        seen.add(rid)
        recs.append({
            'id':            rid,
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'connectionIn':  normalize_connection(r.get('input_connection')),
            'connectionOut': normalize_connection(r.get('output_connection')),
            'opticalPath':   r.get('optical_path_mm'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    for r in raw_ca:
        if not r.get('price_eur'):
            continue
        rid = str(r['astroshop_id'])
        if rid in seen:
            continue
        seen.add(rid)
        recs.append({
            'id':            rid,
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'connectionIn':  normalize_connection(r.get('telescope_connection')),
            'connectionOut': normalize_connection(r.get('camera_mount')),
            'opticalPath':   r.get('optical_path_mm'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'adapters.ts', 'ADAPTERS', 'Adapter', recs)

    # ── Mounts ────────────────────────────────────────────────────────────────
    raw = load(data_dir, 'mounts.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        mt = normalize_mount_type(r.get('mount_type'))
        if mt is None:
            continue
        recs.append({
            'id':             str(r['astroshop_id']),
            'name':           (r.get('full_name') or '')[:60],
            'brand':          r.get('brand') or '',
            'mountType':      mt,
            'payload_kg':     r.get('payload_kg'),
            'includes_tripod': r.get('includes_tripod'),
            'image_url':      r.get('image_url'),
            'price':          r['price_eur'],
            'url':            r.get('url') or '',
        })
    write_ts(out_dir, 'mounts.ts', 'MOUNTS', 'Mount', recs)

    # ── ADCs ──────────────────────────────────────────────────────────────────
    raw = load(data_dir, 'adcs.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        recs.append({
            'id':            str(r['astroshop_id']),
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'connectionIn':  normalize_connection(r.get('telescope_connection')),
            'connectionOut': normalize_connection(r.get('camera_connection')),
            'image_url':     r.get('image_url'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'adcs.ts', 'ADCS', 'ADC', recs)

    # ── Eyepieces ─────────────────────────────────────────────────────────────
    raw = load(data_dir, 'eyepieces.json')
    recs = []
    for r in raw:
        if not r.get('focal_length_mm') or not r.get('price_eur'):
            continue
        recs.append({
            'id':         str(r['astroshop_id']),
            'name':       (r.get('full_name') or '')[:60],
            'brand':      r.get('brand') or '',
            'fl':         r['focal_length_mm'],
            'afov':       r.get('afov_deg'),
            'barrel':     r.get('barrel_diameter_inch'),
            'eye_relief': r.get('eye_relief_mm'),
            'image_url':  r.get('image_url'),
            'price':      r['price_eur'],
            'url':        r.get('url') or '',
        })
    write_ts(out_dir, 'eyepieces.ts', 'EYEPIECES', 'Eyepiece', recs)

    # ── Filters ───────────────────────────────────────────────────────────────
    raw = load(data_dir, 'filters.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        # Derive size string: prefer filter_size_mm, fall back to barrel_diameter_inch
        size_mm = r.get('filter_size_mm')
        barrel = r.get('barrel_diameter_inch')
        if size_mm:
            size = size_mm
        elif barrel:
            size = barrel * 25.4  # convert inches to mm roughly
        else:
            size = None
        recs.append({
            'id':         str(r['astroshop_id']),
            'name':       (r.get('full_name') or '')[:60],
            'brand':      r.get('brand') or '',
            'filterType': r.get('filter_type') or '',
            'size_mm':    size,
            'barrel':     barrel,
            'image_url':  r.get('image_url'),
            'price':      r['price_eur'],
            'url':        r.get('url') or '',
        })
    write_ts(out_dir, 'filters.ts', 'FILTERS', 'Filter', recs)

    # ── Filter Wheels ─────────────────────────────────────────────────────────
    raw = load(data_dir, 'filter_wheels.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        recs.append({
            'id':            str(r['astroshop_id']),
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'positions':     r.get('slot_count'),
            'filterSize':    r.get('filter_slot_size') or '',
            'connectionIn':  normalize_connection(r.get('telescope_connection')),
            'connectionOut': normalize_connection(r.get('camera_connection')),
            'opticalPath':   r.get('optical_path_mm'),
            'image_url':     r.get('image_url'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'filter_wheels.ts', 'FILTER_WHEELS', 'FilterWheel', recs)

    # ── Focusers (includes EAFs / motorized focusers) ─────────────────────────
    raw = load(data_dir, 'focusers.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        recs.append({
            'id':           str(r['astroshop_id']),
            'name':         (r.get('full_name') or '')[:60],
            'brand':        r.get('brand') or '',
            'focuserType':  r.get('focuser_type') or '',
            'travel_mm':    r.get('draw_tube_travel_mm'),
            'connection':   normalize_connection(r.get('telescope_connection')),
            'is_motorized': r.get('is_motorized'),
            'image_url':    r.get('image_url'),
            'price':        r['price_eur'],
            'url':          r.get('url') or '',
        })
    write_ts(out_dir, 'focusers.ts', 'FOCUSERS', 'Focuser', recs)

    # ── OAGs ──────────────────────────────────────────────────────────────────
    raw = load(data_dir, 'oags.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        recs.append({
            'id':            str(r['astroshop_id']),
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'connectionIn':  normalize_connection(r.get('telescope_connection')),
            'connectionOut': normalize_connection(r.get('imaging_connection')),
            'opticalPath':   r.get('optical_path_mm'),
            'image_url':     r.get('image_url'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'oags.ts', 'OAGS', 'OAG', recs)

    # ── Diagonals ─────────────────────────────────────────────────────────────
    raw = load(data_dir, 'diagonals.json')
    recs = []
    for r in raw:
        if not r.get('price_eur'):
            continue
        recs.append({
            'id':            str(r['astroshop_id']),
            'name':          (r.get('full_name') or '')[:60],
            'brand':         r.get('brand') or '',
            'diagonalType':  r.get('diagonal_type') or '',
            'connectionIn':  normalize_connection(r.get('telescope_connection')),
            'connectionOut': barrel_to_connection(r.get('eyepiece_barrel_inch')),
            'opticalPath':   r.get('optical_path_mm'),
            'image_url':     r.get('image_url'),
            'price':         r['price_eur'],
            'url':           r.get('url') or '',
        })
    write_ts(out_dir, 'diagonals.ts', 'DIAGONALS', 'Diagonal', recs)

    # ── Guide Scopes ──────────────────────────────────────────────────────────
    raw = load(data_dir, 'guide_scopes.json')
    recs = []
    for r in raw:
        if not r.get('focal_length_mm') or not r.get('price_eur'):
            continue
        weight_g = r.get('weight_g')
        weight_kg = round(weight_g / 1000, 3) if weight_g else None
        recs.append({
            'id':         str(r['astroshop_id']),
            'name':       (r.get('full_name') or '')[:60],
            'brand':      r.get('brand') or '',
            'aperture':   r.get('aperture_mm'),
            'fl':         r['focal_length_mm'],
            'connection': normalize_connection(r.get('camera_connection')),
            'weight_kg':  weight_kg,
            'image_url':  r.get('image_url'),
            'price':      r['price_eur'],
            'url':        r.get('url') or '',
        })
    write_ts(out_dir, 'guide_scopes.ts', 'GUIDE_SCOPES', 'GuideScope', recs)

    print('\nDone.')


if __name__ == '__main__':
    main()
